# Generated by Django 3.0.8 on 2020-08-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trypincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(default=123456, max_length=10)),
                ('authcode', models.CharField(default='dsadsadas', max_length=100)),
            ],
        ),
    ]
