# Generated by Django 3.0.8 on 2020-08-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trypincode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trypincode',
            name='pincode',
            field=models.IntegerField(default=123456),
        ),
    ]
