# Generated by Django 3.0.8 on 2020-08-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trypincode', '0003_auto_20200804_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trypincode',
            name='authcode',
            field=models.CharField(default='9o5p5d51kcjhx1zn3ry16tgpxys5muj64clu2wgf0rbmj2rj0wsmmo3jx116xhkjxa6matc5ks8f41cbl4dv0fa7zb6tk8mplrdygk3kzbr9pomjaw19g2u1h4d58r9b', max_length=200),
        ),
    ]
