# Generated by Django 3.0.8 on 2020-08-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trypincode', '0004_auto_20200804_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='trypincode',
            name='email',
            field=models.EmailField(default=321, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trypincode',
            name='pwd',
            field=models.CharField(default=231, max_length=100),
            preserve_default=False,
        ),
    ]
