# Generated by Django 3.0.8 on 2020-08-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trypincode', '0005_auto_20200805_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='trypincode',
            name='techID',
            field=models.IntegerField(default=1234567),
        ),
    ]
