# Generated by Django 3.0.8 on 2020-08-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trypincode', '0006_trypincode_techid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trypincode',
            name='channel',
            field=models.CharField(default='CHANNEL01', max_length=200),
        ),
    ]
